classdef UpdateParameters
    properties (Constant, Access = private)
        calcGeom   = GeometricParametersCalculator();
        calcConc   = ConcentrationParametersCalculator();
        calcKin    = KineticParametersCalculator();
        calcTherm  = ThermodynamicParametersCalculator();        
        calcElec   = ElectricalParametersCalculator();
    end
    methods(Static)
        %% Update Values of Parameters
        function battery = updateNegativeElectrodeParams(battery, electrode, applied_current, ...
                preComputedMatrix, ...
                timeStep, ...
                time)

            % Compute Active material volume fraction
            battery.GeometricParams.electrode.negative.volumeFractionLAM_derivation_neg(time+1, :) = ...
                    UpdateParameters.calcGeom.compute_electrode_volumeFractionLAM_derivation(battery, ...
                        applied_current, ...
                        electrode);

            battery.GeometricParams.electrode.negative.active_material_volume_fraction_neg(time+1, :) = ...
                    UpdateParameters.calcGeom.compute_electrode_volumeFraction( ...
                        battery.GeometricParams.electrode.negative.active_material_volume_fraction_neg(time, :), ...
                        battery.GeometricParams.electrode.negative.volumeFractionLAM_derivation_neg(time+1, :), ...
                        timeStep);

            % Compute specific interfacial surface area
            battery.GeometricParams.electrode.negative.particles.specific_interfacial_surface_area_neg(time+1, :) = ...
                UpdateParameters.calcGeom.compute_specific_interfacial_surface_area( ...
                    battery.GeometricParams.electrode.negative.particles.particle_radius_neg, ...
                    battery.GeometricParams.electrode.negative.active_material_volume_fraction_neg(time+1, :));
        
            % Compute molar ionic flux                 
            battery.KineticParams.electrode.negative.molar_ionic_flux_neg(time+1,:) = UpdateParameters.calcKin.compute_molar_ionic_flux( ...
                battery, applied_current, ...
                battery.GeometricParams.electrode.negative.particles.specific_interfacial_surface_area_neg(time+1, :), ...
                electrode);           

            % Compute electrode concentration
            battery.ConcentrationParams.electrode.negative.concentration_neg(:,time+1) = UpdateParameters.calcConc.compute_electrode_concentration( ...
                preComputedMatrix.electrode.negative.Acs_hat, ...
                preComputedMatrix.electrode.negative.boundaryConcentrationDiscreteTimeMatrix, ...
                battery.ConcentrationParams.electrode.negative.concentration_neg(:,time), ...
                battery.KineticParams.electrode.negative.molar_ionic_flux_neg(time+1,:));
    
            % Surface Concentration
            battery.ConcentrationParams.electrode.negative.surface_concentration_neg(time+1,:) = UpdateParameters.calcConc.compute_electrode_surface_concentration( ...
                battery.ConcentrationParams.electrode.negative.concentration_neg(:,time+1), preComputedMatrix.electrode.negative.Acs_bar);
            
            % Average Concentration
            battery.ConcentrationParams.electrode.negative.average_concentration_neg(time+1,:) = UpdateParameters.calcConc.compute_electrode_average_concentration( ...
                    battery, battery.ConcentrationParams.electrode.negative.concentration_neg(:,time+1), electrode);
    
            % Compute Aging stoichiometry
            battery.ThermodynamicParams.electrode.negative.aging_stoichiometry_neg(time+1,:) = UpdateParameters.calcTherm.compute_aging_stoichiometry( ...
                battery.ConcentrationParams.electrode.negative.average_concentration_neg(time+1,:), ...
                battery.ConcentrationParams.electrode.negative.concentration_maximum_neg);
    
            % Compute stoichiometry
            battery.ThermodynamicParams.electrode.negative.stoichiometry_neg(time+1,:) = UpdateParameters.calcTherm.compute_stoichiometry( ...
                battery.ConcentrationParams.electrode.negative.surface_concentration_neg(time+1,:), ...
                battery.ConcentrationParams.electrode.negative.concentration_maximum_neg);
            
            % Compute equilibrium potential
            battery.ThermodynamicParams.electrode.negative.equilibrium_potential_neg(time+1,:) = ...
                UpdateParameters.calcTherm.compute_electrode_equilibrium_potential( ...
                battery.ThermodynamicParams.electrode.negative.equilibrium_potential_equation_neg, ...
                battery.ThermodynamicParams.electrode.negative.stoichiometry_neg(time+1,:));
        end

        %% Update Values of Parameters
        % Update Values of Parameters
        function battery = updatePositiveElectrodeParams(battery, electrode, applied_current, ...
                                                preComputedMatrix, ...
                                                timeStep, ...
                                                time)
          
            % Compute Active material volume fraction
            battery.GeometricParams.electrode.positive.volumeFractionLAM_derivation_pos(time+1, :) = ...
                    UpdateParameters.calcGeom.compute_electrode_volumeFractionLAM_derivation(battery, ...
                        applied_current, ...
                        electrode);

            battery.GeometricParams.electrode.positive.active_material_volume_fraction_pos(time+1, :) = ...
                    UpdateParameters.calcGeom.compute_electrode_volumeFraction( ...
                        battery.GeometricParams.electrode.positive.active_material_volume_fraction_pos(time, :), ...
                        battery.GeometricParams.electrode.positive.volumeFractionLAM_derivation_pos(time+1, :), ...
                        timeStep);

            % Compute specific interfacial surface area
            battery.GeometricParams.electrode.positive.particles.specific_interfacial_surface_area_pos(time+1, :) = ...
                UpdateParameters.calcGeom.compute_specific_interfacial_surface_area( ...,
                                battery.GeometricParams.electrode.positive.particles.particle_radius_pos, ...
                                battery.GeometricParams.electrode.positive.active_material_volume_fraction_pos(time+1, :));
        
            % Compute molar ionic flux                 
            battery.KineticParams.electrode.positive.molar_ionic_flux_pos(time+1,:) = UpdateParameters.calcKin.compute_molar_ionic_flux( ...
                battery, applied_current, ...
                battery.GeometricParams.electrode.positive.particles.specific_interfacial_surface_area_pos(time+1, :), ...
                electrode);           

            % Compute electrode concentration
            battery.ConcentrationParams.electrode.positive.concentration_pos(:,time+1) = UpdateParameters.calcConc.compute_electrode_concentration( ...
                preComputedMatrix.electrode.positive.Acs_hat, ...
                preComputedMatrix.electrode.positive.boundaryConcentrationDiscreteTimeMatrix, ...
                battery.ConcentrationParams.electrode.positive.concentration_pos(:,time), ...
                battery.KineticParams.electrode.positive.molar_ionic_flux_pos(time+1,:));
    
            % Surface Concentration
            battery.ConcentrationParams.electrode.positive.surface_concentration_pos(time+1,:) = UpdateParameters.calcConc.compute_electrode_surface_concentration( ...
                battery.ConcentrationParams.electrode.positive.concentration_pos(:,time+1), preComputedMatrix.electrode.positive.Acs_bar);
            
            % Average Concentration
            battery.ConcentrationParams.electrode.positive.average_concentration_pos(time+1,:) = UpdateParameters.calcConc.compute_electrode_average_concentration( ...
                    battery, battery.ConcentrationParams.electrode.positive.concentration_pos(:,time+1), electrode);
    
            % Compute Aging stoichiometry
            battery.ThermodynamicParams.electrode.positive.aging_stoichiometry_pos(time+1,:) = UpdateParameters.calcTherm.compute_aging_stoichiometry( ...
                battery.ConcentrationParams.electrode.positive.average_concentration_pos(time+1,:), ...
                battery.ConcentrationParams.electrode.positive.concentration_maximum_pos);
    
            % Compute stoichiometry
            battery.ThermodynamicParams.electrode.positive.stoichiometry_pos(time+1,:) = UpdateParameters.calcTherm.compute_stoichiometry( ...
                battery.ConcentrationParams.electrode.positive.surface_concentration_pos(time+1,:), ...
                battery.ConcentrationParams.electrode.positive.concentration_maximum_pos);
            
            % Compute equilibrium potential
            battery.ThermodynamicParams.electrode.positive.equilibrium_potential_pos(time+1,:) = ...
                UpdateParameters.calcTherm.compute_electrode_equilibrium_potential( ...
                battery.ThermodynamicParams.electrode.positive.equilibrium_potential_equation_pos, ...
                battery.ThermodynamicParams.electrode.positive.stoichiometry_pos(time+1,:));

        end

        %% Helper function for Electrolyte Parameters Update
        function battery = updateElectrolyteParams(battery, preComputedMatrix, time)

            % Compute Elelctrolyte Concentration 
            battery.ConcentrationParams.electrolyte.concentration_elyte(:, time+1) = ...
                UpdateParameters.calcConc.compute_electrolyte_concentration( ...
                preComputedMatrix.electrolyte.surfaceDiffusionElyteDiscreteTime, ...
                preComputedMatrix.electrolyte.boundaryFluxElectrolyteDiscreteTime, ...
                battery.KineticParams.electrode.negative.molar_ionic_flux_neg(time+1, :), ...
                battery.KineticParams.electrode.positive.molar_ionic_flux_pos(time+1, :), ...
                battery.ConcentrationParams.electrolyte.concentration_elyte(:, time));

            % Compute Mean Elelctrolyte Concentration 
            battery.ConcentrationParams.electrolyte.concentration_mean_elyte_neg(time+1,:) = ...
                UpdateParameters.calcConc.compute_electrolyte_mean_concentration(battery,"negative", ...
                battery.ConcentrationParams.electrolyte.concentration_elyte(:,time+1));

            battery.ConcentrationParams.electrolyte.concentration_mean_elyte_pos(time+1,:) = ...
                UpdateParameters.calcConc.compute_electrolyte_mean_concentration(battery,"positive", ...
                battery.ConcentrationParams.electrolyte.concentration_elyte(:,time+1));

         % Compute Elelctrolyte Potential 
            battery.ThermodynamicParams.electrolyte.potential_elyte(:,time+1) = ...
                UpdateParameters.calcTherm.compute_electrolyte_potential( ...
                    preComputedMatrix.electrolyte.boundaryPotentialElyteDiscreteTime, ...
                    preComputedMatrix.electrolyte.surfacePotentialElyteMatrix, ...
                    preComputedMatrix.electrolyte.diffusionPotentialElyteMatrix, ...
                    battery.KineticParams.electrode.negative.molar_ionic_flux_neg(time+1,:), ...
                    battery.KineticParams.electrode.positive.molar_ionic_flux_pos(time+1,:), ...
                    battery.ConcentrationParams.electrolyte.concentration_elyte(:,time+1));
            
           % Compute Mean Elelctrolyte Potential         
           battery.ThermodynamicParams.electrolyte.potential_mean_elyte_neg(time+1,:) = ...
               UpdateParameters.calcTherm.compute_electrolyte_mean_potential(battery, ...
               battery.ThermodynamicParams.electrolyte.potential_elyte(:,time+1),"negative");
           battery.ThermodynamicParams.electrolyte.potential_mean_elyte_pos(time+1,:) = ...
               UpdateParameters.calcTherm.compute_electrolyte_mean_potential(battery, ...
               battery.ThermodynamicParams.electrolyte.potential_elyte(:,time+1),"positive");
        end
       

        %% Helper function for Aging Parameters Update
        function battery = updateAgingSEIParams(battery, timeStep, time)
    
            electrode = "negative";
    
            % SEI thickness increase
            battery.GeometricParams.electrode.negative.SEI_inner_thickness_increased_neg(time+1, :) = ...
                UpdateParameters.calcGeom.compute_SEI_inner_thickness_increased( ...
                battery, battery.KineticParams.electrode.negative.SEI_tunneling_reaction_rate_neg(time, :), ...
                battery.GeometricParams.electrode.negative.sei_thickness_ratio_neg, timeStep);
    
            % Compute SEI thickness total
            battery.GeometricParams.electrode.negative.SEI_inner_thickness_total_neg(time+1, :) = ...
                UpdateParameters.calcGeom.compute_SEI_inner_thickness_total( ...
                    battery.GeometricParams.electrode.negative.SEI_inner_thickness_total_neg(time, :), ...
                    battery.GeometricParams.electrode.negative.SEI_inner_thickness_increased_neg(time+1, :));
    
            % Compute SEI tunneling reaction rate
            % Lithium loss due to SEI
            battery.KineticParams.electrode.negative.SEI_tunneling_reaction_rate_neg(time+1, :) = ...
                UpdateParameters.calcKin.compute_SEI_electron_tunneling_rate( ...
                battery, electrode, battery.ThermodynamicParams.electrode.negative.aging_stoichiometry_neg(time+1, :), ...
                battery.GeometricParams.electrode.negative.SEI_inner_thickness_total_neg(time+1, :));
    
            % Compute Lithium Loss SEI Formation
             battery.KineticParams.electrode.negative.Lithium_loss_SEI_formation_neg(time+1, :) = ...
                 UpdateParameters.calcKin.compute_Lithium_loss_SEI_formation( ...
                 battery.KineticParams.electrode.negative.Lithium_loss_SEI_formation_neg(time, :), ...
                 battery.GeometricParams.electrode.negative.particles.specific_interfacial_surface_area_neg(time+1, :), ...
                 battery.KineticParams.electrode.negative.SEI_tunneling_reaction_rate_neg(time+1, :), timeStep);
    
            % Film resistance
            battery.ElectricalParams.electrode.negative.sei_film_resistance_neg(time+1, :) = ...
                UpdateParameters.calcElec.compute_filmResistance(battery, ...
                        battery.GeometricParams.electrode.negative.SEI_inner_thickness_total_neg(time+1, :), electrode);
            
            % Capacity loss components
            battery.ElectricalParams.electrode.negative.capacityLossSEI_neg(time+1, :) = ...
                UpdateParameters.calcElec.calculate_capacityLoss_SEI(battery, ...
                        battery.KineticParams.electrode.negative.Lithium_loss_SEI_formation_neg(time+1, :));
        end

        %% Helper function for Aging Parameters Update
        function battery = updateNegativeAgingLAMParams(battery, electrode, timeStep, time)

                 battery.ElectricalParams.electrode.negative.capacityLossLAM_neg(time+1, :) = ...
                     UpdateParameters.calcElec.calculate_capacityLoss_LAM(battery, ...
                            battery.ElectricalParams.electrode.negative.capacityLossLAM_neg(time, :), ...
                            battery.GeometricParams.electrode.negative.volumeFractionLAM_derivation_neg(time+1, :), ...
                            battery.ThermodynamicParams.electrode.negative.aging_stoichiometry_neg(time+1, :), ...
                            electrode, timeStep);
        
        end

        %% Helper function for Aging Parameters Update
        function battery = updatePositiveAgingLAMParams(battery, electrode, timeStep, time)

                 battery.ElectricalParams.electrode.positive.capacityLossLAM_pos(time+1, :) = ...
                     UpdateParameters.calcElec.calculate_capacityLoss_LAM(battery, ...
                            battery.ElectricalParams.electrode.positive.capacityLossLAM_pos(time, :), ...
                            battery.GeometricParams.electrode.positive.volumeFractionLAM_derivation_pos(time+1, :), ...
                            battery.ThermodynamicParams.electrode.positive.aging_stoichiometry_pos(time+1, :), ...
                            electrode, timeStep);
        
        end

        %% Helper function for Electrode Parameters Update
        function battery = updateRestNegativeElectrodeParams(battery, electrode, time)

            sei_film_resistance = battery.ElectricalParams.electrode.negative.sei_film_resistance_neg(time+1, :);
            
            battery.KineticParams.electrode.negative.exchange_current_density_neg(time+1, :) = ...
                UpdateParameters.calcKin.compute_exchange_current_density(battery, ...
                        battery.ConcentrationParams.electrode.negative.surface_concentration_neg(time+1, :), ...
                        battery.ConcentrationParams.electrolyte.concentration_mean_elyte_neg(time+1, :), ...
                        electrode);
    
            battery.ThermodynamicParams.electrode.negative.overpotential_neg(time+1, :) = ...
                UpdateParameters.calcTherm.compute_electrode_overpotential(battery, ...
                battery.KineticParams.electrode.negative.molar_ionic_flux_neg(time+1, :), ...
                battery.KineticParams.electrode.negative.exchange_current_density_neg(time+1, :), ...
                 battery.ThermodynamicParams.electrolyte.potential_mean_elyte_neg(time+1, :), ...
                sei_film_resistance, electrode);   
    
            battery.ThermodynamicParams.electrode.negative.potential_neg(time+1, :) = ...
                UpdateParameters.calcTherm.compute_electrode_potential( ...
                battery.ThermodynamicParams.electrode.negative.overpotential_neg(time+1, :), ...
                battery.ThermodynamicParams.electrode.negative.equilibrium_potential_neg(time+1, :));
    
        end
    
        %% Helper function for Electrode Parameters Update
        function battery = updateRestPositiveElectrodeParams(battery, electrode, time)
            sei_film_resistance = battery.ElectricalParams.electrode.positive.sei_film_resistance_pos(1, :);
    
            battery.KineticParams.electrode.positive.exchange_current_density_pos(time+1, :) = ...
                UpdateParameters.calcKin.compute_exchange_current_density(battery, ...
                        battery.ConcentrationParams.electrode.positive.surface_concentration_pos(time+1, :), ...
                        battery.ConcentrationParams.electrolyte.concentration_mean_elyte_pos(time+1, :), ...
                        electrode);
    
            battery.ThermodynamicParams.electrode.positive.overpotential_pos(time+1, :) = ...
                UpdateParameters.calcTherm.compute_electrode_overpotential(battery, ...
                battery.KineticParams.electrode.positive.molar_ionic_flux_pos(time+1, :), ...
                battery.KineticParams.electrode.positive.exchange_current_density_pos(time+1, :), ...
                 battery.ThermodynamicParams.electrolyte.potential_mean_elyte_pos(time+1, :), ...
                sei_film_resistance, electrode);   
    
            battery.ThermodynamicParams.electrode.positive.potential_pos(time+1, :) = ...
                UpdateParameters.calcTherm.compute_electrode_potential( ...
                battery.ThermodynamicParams.electrode.positive.overpotential_pos(time+1, :), ...
                battery.ThermodynamicParams.electrode.positive.equilibrium_potential_pos(time+1, :));
    
        end
        
        %% Helper function for Electrode Parameters Update
        function battery = updateCellAgingParams(battery, applied_current, cycleNum, timeStep, time)
            
                % ========== Update Cell voltage
                battery.ElectricalParams.cell.voltage(time+1,:) = UpdateParameters.calcElec.compute_cell_voltage(battery, ...
                    applied_current, time);
    
                % ========== Update SOC
                battery.ElectricalParams.cell.SOC(time+1,:) = UpdateParameters.calcElec.compute_SOC(battery, ...
                    applied_current, ...
                    battery.ElectricalParams.cell.SOC(time,:), ...
                    battery.ElectricalParams.cell.battery_capacity_cell(cycleNum,1), cycleNum, timeStep, time);
            
                % ========== Update Cpacity Loss
                battery.ElectricalParams.cell.total_capacityLoss(time+1,:) = ...
                    UpdateParameters.calcElec.compute_total_capacityLoss( ...
                        battery.ElectricalParams.electrode.negative.capacityLossLAM_neg(time+1,:), ...
                        battery.ElectricalParams.electrode.positive.capacityLossLAM_pos(time+1,:), ...
                        battery.ElectricalParams.electrode.negative.capacityLossSEI_neg(time+1,:));
        end

    end    
end