classdef ESPMsimulation

    properties (Constant, Access = private)
        calcGeom   = GeometricParametersCalculator();
        calcConc   = ConcentrationParametersCalculator();
        calcKin    = KineticParametersCalculator();
        calcTherm  = ThermodynamicParametersCalculator();        
        calcElec   = ElectricalParametersCalculator();
    end
    
    methods(Static)
        %% ESPM Simulation Full-Cell Analysis
        function battery = runESPMsimulation(battery, PreComPM, applied_current, timeSize, timeStep)
           
            % ============================
            % === 1) One-time setup  ====
            % ============================
            t0 = tic;
            % =====================================
            % === 2) Time integration main loop ===
            % =====================================
            time = 1;
            timeVector = zeros(timeSize,1);
            simulationEnd = 0;

            while simulationEnd ~= 1
                battery = ESPMsimulation.updateNegativeElectrodeParams(battery, "negative", ...                    
                    applied_current(time+1), PreComPM, timeStep, time);

                battery = ESPMsimulation.updatePositiveElectrodeParams(battery, "positive", applied_current(time+1), ...
                    PreComPM, timeStep, time);
                
                battery = ESPMsimulation.updateElectrolyteParams(battery, PreComPM, time);

                battery = ESPMsimulation.updateRestNegativeElectrodeParams(battery, "negative", time);
                battery = ESPMsimulation.updateRestPositiveElectrodeParams(battery, "positive", time);

                % ========= Termination Conditions ==========
                if timeStep < 1e-60
                    break;
                end

                if simulationEnd || time >= timeSize-1 || time >= length(applied_current), break; end

                timeVector(time+1, :) = timeVector(time, :) + timeStep;
                time = time + 1;

            end
            
            battery.SimulationParams.runtime = toc(t0);

            battery.SimulationParams.timeVector = timeVector' ;
            battery.ElectricalParams.cell.applied_current = applied_current(2:end);

            % Compute cell capacity for full simulation
             battery.ElectricalParams.cell.cell_capacity = ...
                  ESPMsimulation.calcElec.compute_Cell_Capacity(battery);
        end

        %% Update Values of Parameters
        function battery = updateNegativeElectrodeParams(battery, electrode, applied_current, ...
                preComputedMatrix, timeStep, time)

            % Compute Active material volume fraction
            battery.GeometricParams.electrode.negative.volumeFractionLAM_derivation_neg(time+1, :) = ...
                    ESPMsimulation.calcGeom.compute_electrode_volumeFractionLAM_derivation(battery, ...
                        applied_current, ...
                        electrode);

            battery.GeometricParams.electrode.negative.active_material_volume_fraction_neg(time+1, :) = ...
                    ESPMsimulation.calcGeom.compute_electrode_volumeFraction( ...
                        battery.GeometricParams.electrode.negative.active_material_volume_fraction_neg(time), ...
                        battery.GeometricParams.electrode.negative.volumeFractionLAM_derivation_neg(time+1), ...
                        timeStep);

            % Compute specific interfacial surface area
            battery.GeometricParams.electrode.negative.particles.specific_interfacial_surface_area_neg(time+1, :) = ...
                ESPMsimulation.calcGeom.compute_specific_interfacial_surface_area( ...
                    battery.GeometricParams.electrode.negative.particles.particle_radius_neg, ...
                    battery.GeometricParams.electrode.negative.active_material_volume_fraction_neg(time+1));
        
            % Compute molar ionic flux                 
            battery.KineticParams.electrode.negative.molar_ionic_flux_neg(time+1, :) = ESPMsimulation.calcKin.compute_molar_ionic_flux( ...
                battery, applied_current, ...
                battery.GeometricParams.electrode.negative.particles.specific_interfacial_surface_area_neg(time+1), ...
                electrode);           

            % Compute electrode concentration
            battery.ConcentrationParams.electrode.negative.concentration_neg(:,time+1) = ESPMsimulation.calcConc.compute_electrode_concentration( ...
                preComputedMatrix.electrode.negative.Acs_hat, ...
                preComputedMatrix.electrode.negative.boundaryConcentrationDiscreteTimeMatrix, ...
                battery.ConcentrationParams.electrode.negative.concentration_neg(:,time), ...
                battery.KineticParams.electrode.negative.molar_ionic_flux_neg(time+1));
    
            % Surface Concentration
            battery.ConcentrationParams.electrode.negative.surface_concentration_neg(time+1, :) = ESPMsimulation.calcConc.compute_electrode_surface_concentration( ...
                battery.ConcentrationParams.electrode.negative.concentration_neg(:,time+1), preComputedMatrix.electrode.negative.Acs_bar);
            
            % Average Concentration
            battery.ConcentrationParams.electrode.negative.average_concentration_neg(time+1, :) = ESPMsimulation.calcConc.compute_electrode_average_concentration( ...
                    battery, battery.ConcentrationParams.electrode.negative.concentration_neg(:,time+1), electrode);
    
            % Compute Aging stoichiometry
            battery.ThermodynamicParams.electrode.negative.aging_stoichiometry_neg(time+1, :) = ESPMsimulation.calcTherm.compute_aging_stoichiometry( ...
                battery.ConcentrationParams.electrode.negative.average_concentration_neg(time+1), ...
                battery.ConcentrationParams.electrode.negative.concentration_maximum_neg);
    
            % Compute stoichiometry
            battery.ThermodynamicParams.electrode.negative.stoichiometry_neg(time+1, :) = ESPMsimulation.calcTherm.compute_stoichiometry( ...
                battery.ConcentrationParams.electrode.negative.surface_concentration_neg(time+1), ...
                battery.ConcentrationParams.electrode.negative.concentration_maximum_neg);
            
            % Compute equilibrium potential
            battery.ThermodynamicParams.electrode.negative.equilibrium_potential_neg(time+1, :) = ...
                ESPMsimulation.calcTherm.compute_electrode_equilibrium_potential( ...
                battery.ThermodynamicParams.electrode.negative.equilibrium_potential_equation_neg, ...
                battery.ThermodynamicParams.electrode.negative.stoichiometry_neg(time+1));
        end

        %% Update Values of Parameters
        % Update Values of Parameters
        function battery = updatePositiveElectrodeParams(battery, electrode, applied_current, ...
            preComputedMatrix, timeStep, time)
          
            % Compute Active material volume fraction
            battery.GeometricParams.electrode.positive.volumeFractionLAM_derivation_pos(time+1, :) = ...
                    ESPMsimulation.calcGeom.compute_electrode_volumeFractionLAM_derivation(battery, ...
                        applied_current, ...
                        electrode);

            battery.GeometricParams.electrode.positive.active_material_volume_fraction_pos(time+1, :) = ...
                    ESPMsimulation.calcGeom.compute_electrode_volumeFraction( ...
                        battery.GeometricParams.electrode.positive.active_material_volume_fraction_pos(time), ...
                        battery.GeometricParams.electrode.positive.volumeFractionLAM_derivation_pos(time+1), ...
                        timeStep);

            % Compute specific interfacial surface area
            battery.GeometricParams.electrode.positive.particles.specific_interfacial_surface_area_pos(time+1, :) = ...
                ESPMsimulation.calcGeom.compute_specific_interfacial_surface_area( ...,
                                battery.GeometricParams.electrode.positive.particles.particle_radius_pos, ...
                                battery.GeometricParams.electrode.positive.active_material_volume_fraction_pos(time+1));
        
            % Compute molar ionic flux                 
            battery.KineticParams.electrode.positive.molar_ionic_flux_pos(time+1, :) = ESPMsimulation.calcKin.compute_molar_ionic_flux( ...
                battery, applied_current, ...
                battery.GeometricParams.electrode.positive.particles.specific_interfacial_surface_area_pos(time+1), ...
                electrode);           

            % Compute electrode concentration
            battery.ConcentrationParams.electrode.positive.concentration_pos(:,time+1) = ESPMsimulation.calcConc.compute_electrode_concentration( ...
                preComputedMatrix.electrode.positive.Acs_hat, ...
                preComputedMatrix.electrode.positive.boundaryConcentrationDiscreteTimeMatrix, ...
                battery.ConcentrationParams.electrode.positive.concentration_pos(:,time), ...
                battery.KineticParams.electrode.positive.molar_ionic_flux_pos(time+1));
    
            % Surface Concentration
            battery.ConcentrationParams.electrode.positive.surface_concentration_pos(time+1, :) = ESPMsimulation.calcConc.compute_electrode_surface_concentration( ...
                battery.ConcentrationParams.electrode.positive.concentration_pos(:,time+1), preComputedMatrix.electrode.positive.Acs_bar);
            
            % Average Concentration
            battery.ConcentrationParams.electrode.positive.average_concentration_pos(time+1, :) = ESPMsimulation.calcConc.compute_electrode_average_concentration( ...
                    battery, battery.ConcentrationParams.electrode.positive.concentration_pos(:,time+1), electrode);
    
            % Compute Aging stoichiometry
            battery.ThermodynamicParams.electrode.positive.aging_stoichiometry_pos(time+1, :) = ESPMsimulation.calcTherm.compute_aging_stoichiometry( ...
                battery.ConcentrationParams.electrode.positive.average_concentration_pos(time+1), ...
                battery.ConcentrationParams.electrode.positive.concentration_maximum_pos);
    
            % Compute stoichiometry
            battery.ThermodynamicParams.electrode.positive.stoichiometry_pos(time+1, :) = ESPMsimulation.calcTherm.compute_stoichiometry( ...
                battery.ConcentrationParams.electrode.positive.surface_concentration_pos(time+1), ...
                battery.ConcentrationParams.electrode.positive.concentration_maximum_pos);
            
            % Compute equilibrium potential
            battery.ThermodynamicParams.electrode.positive.equilibrium_potential_pos(time+1, :) = ...
                ESPMsimulation.calcTherm.compute_electrode_equilibrium_potential( ...
                battery.ThermodynamicParams.electrode.positive.equilibrium_potential_equation_pos, ...
                battery.ThermodynamicParams.electrode.positive.stoichiometry_pos(time+1));

        end

        %% Helper function for Electrolyte Parameters Update
        function battery = updateElectrolyteParams(battery, preComputedMatrix, time)

            % Compute Elelctrolyte Concentration 
            battery.ConcentrationParams.electrolyte.concentration_elyte(:, time+1) = ...
                ESPMsimulation.calcConc.compute_electrolyte_concentration( ...
                preComputedMatrix.electrolyte.surfaceDiffusionElyteDiscreteTime, ...
                preComputedMatrix.electrolyte.boundaryFluxElectrolyteDiscreteTime, ...
                battery.KineticParams.electrode.negative.molar_ionic_flux_neg(time+1), ...
                battery.KineticParams.electrode.positive.molar_ionic_flux_pos(time+1), ...
                battery.ConcentrationParams.electrolyte.concentration_elyte(:, time));

            % Compute Mean Elelctrolyte Concentration 
            battery.ConcentrationParams.electrolyte.concentration_mean_elyte_neg(time+1, :) = ...
                ESPMsimulation.calcConc.compute_electrolyte_mean_concentration(battery,"negative", ...
                battery.ConcentrationParams.electrolyte.concentration_elyte(:,time+1));

            battery.ConcentrationParams.electrolyte.concentration_mean_elyte_pos(time+1, :) = ...
                ESPMsimulation.calcConc.compute_electrolyte_mean_concentration(battery,"positive", ...
                battery.ConcentrationParams.electrolyte.concentration_elyte(:,time+1));

         % Compute Elelctrolyte Potential 
            battery.ThermodynamicParams.electrolyte.potential_elyte(:,time+1) = ...
                ESPMsimulation.calcTherm.compute_electrolyte_potential( ...
                    preComputedMatrix.electrolyte.boundaryPotentialElyteDiscreteTime, ...
                    preComputedMatrix.electrolyte.surfacePotentialElyteMatrix, ...
                    preComputedMatrix.electrolyte.diffusionPotentialElyteMatrix, ...
                    battery.KineticParams.electrode.negative.molar_ionic_flux_neg(time+1), ...
                    battery.KineticParams.electrode.positive.molar_ionic_flux_pos(time+1), ...
                    battery.ConcentrationParams.electrolyte.concentration_elyte(:,time+1));
            
           % Compute Mean Elelctrolyte Potential         
           battery.ThermodynamicParams.electrolyte.potential_mean_elyte_neg(time+1, :) = ...
               ESPMsimulation.calcTherm.compute_electrolyte_mean_potential(battery, ...
               battery.ThermodynamicParams.electrolyte.potential_elyte(:,time+1),"negative");
           battery.ThermodynamicParams.electrolyte.potential_mean_elyte_pos(time+1, :) = ...
               ESPMsimulation.calcTherm.compute_electrolyte_mean_potential(battery, ...
               battery.ThermodynamicParams.electrolyte.potential_elyte(:,time+1),"positive");
        end

        %% Helper function for Electrode Parameters Update
        function battery = updateRestNegativeElectrodeParams(battery, electrode, time)

            sei_film_resistance = battery.ElectricalParams.electrode.negative.sei_film_resistance_neg(time+1);
            
            battery.KineticParams.electrode.negative.exchange_current_density_neg(time+1, :) = ...
                ESPMsimulation.calcKin.compute_exchange_current_density(battery, ...
                        battery.ConcentrationParams.electrode.negative.surface_concentration_neg(time+1), ...
                        battery.ConcentrationParams.electrolyte.concentration_mean_elyte_neg(time+1), ...
                        electrode);
    
            battery.ThermodynamicParams.electrode.negative.overpotential_neg(time+1, :) = ...
                ESPMsimulation.calcTherm.compute_electrode_overpotential(battery, ...
                battery.KineticParams.electrode.negative.molar_ionic_flux_neg(time+1), ...
                battery.KineticParams.electrode.negative.exchange_current_density_neg(time+1), ...
                 battery.ThermodynamicParams.electrolyte.potential_mean_elyte_neg(time+1), ...
                sei_film_resistance, electrode);   
    
            battery.ThermodynamicParams.electrode.negative.potential_neg(time+1, :) = ...
                ESPMsimulation.calcTherm.compute_electrode_potential( ...
                battery.ThermodynamicParams.electrode.negative.overpotential_neg(time+1), ...
                battery.ThermodynamicParams.electrode.negative.equilibrium_potential_neg(time+1));
    
        end
    
        %% Helper function for Electrode Parameters Update
        function battery = updateRestPositiveElectrodeParams(battery, electrode, time)
            sei_film_resistance = battery.ElectricalParams.electrode.positive.sei_film_resistance_pos(1);
    
            battery.KineticParams.electrode.positive.exchange_current_density_pos(time+1, :) = ...
                ESPMsimulation.calcKin.compute_exchange_current_density(battery, ...
                        battery.ConcentrationParams.electrode.positive.surface_concentration_pos(time+1), ...
                        battery.ConcentrationParams.electrolyte.concentration_mean_elyte_pos(time+1), ...
                        electrode);
    
            battery.ThermodynamicParams.electrode.positive.overpotential_pos(time+1, :) = ...
                ESPMsimulation.calcTherm.compute_electrode_overpotential(battery, ...
                battery.KineticParams.electrode.positive.molar_ionic_flux_pos(time+1), ...
                battery.KineticParams.electrode.positive.exchange_current_density_pos(time+1), ...
                 battery.ThermodynamicParams.electrolyte.potential_mean_elyte_pos(time+1), ...
                sei_film_resistance, electrode);   
    
            battery.ThermodynamicParams.electrode.positive.potential_pos(time+1, :) = ...
                ESPMsimulation.calcTherm.compute_electrode_potential( ...
                battery.ThermodynamicParams.electrode.positive.overpotential_pos(time+1), ...
                battery.ThermodynamicParams.electrode.positive.equilibrium_potential_pos(time+1));
    
        end
        
        %% Helper function for Electrode Parameters Update
        function battery = updateCell(battery, applied_current, cycleNum, timeStep, time)
            
                % ========== Update Cell voltage
                battery.ElectricalParams.cell.voltage(time+1, :) = ESPMsimulation.calcElec.compute_cell_voltage(battery, ...
                    applied_current, time);
    
                % ========== Update SOC
                battery.ElectricalParams.cell.SOC(time+1, :) = ESPMsimulation.calcElec.compute_SOC(battery, ...
                    applied_current, ...
                    battery.ElectricalParams.cell.SOC(time), ...
                    battery.ElectricalParams.cell.battery_capacity_cell(cycleNum,1), timeStep);

        end
     
    end
end
