function simulation( ...
    battery, ...
    SOC_initial, ...
    applied_current, ...
    current_mode, ...
    dischargeC_rate, ...
    chargeC_rate, ...
    cycle_startmode, ...
    temperature, ...
    aging_mode, ...
    timeFinal, ...
    timeStep, ...
    dischargeTimeStep, ...
    chargeTimeStep, ...
    CVTimeStep, ...
    restDuration, ...
    CCCVstatus, ...
    current_cutoff, ...
    cycleTotalNum, ...
    parallelCellNum, ...
    seriesCellNum);

    %% Validate battery structure
    if isempty(battery), error('Battery parameter structure is required.'); end

    %% Set default values for optional inputs
    if isnan(SOC_initial), SOC_initial = 1; end
    if isnan(timeFinal), timeFinal = 3600; end
    if isnan(timeStep), timeStep = 1; end
    if isnan(temperature) || isempty(temperature)
        temperature = 298.15;   % Default to 25°C in Kelvin
    else
        temperature = temperature + 273.15; % Convert °C to Kelvin
    end

    if isnan(aging_mode), aging_mode = 1; end
    if isnan(cycleTotalNum), cycleTotalNum = 1; end

    %% Validate SOC_initial configuration
    % Check if value is a string and contains '%'
    if ischar(SOC_initial) || isstring(SOC_initial)
        if contains(SOC_initial, '%')
            valueStr = strrep(SOC_initial, '%', ''); % Remove %
            SOC_initial = str2double(valueStr) / 100;    % Convert to number
        else
            SOC_initial = str2double(SOC_initial);          % Convert directly
        end
    end

    %% working electrode configuration
    working_electrode = ["negative", "positive"];
    
   %% Store simulation parameters in battery struct

    % Simulation start time in seconds
    timeStart = 1;
    battery.SimulationParams = struct( ...
        'SOC_initial', SOC_initial, ...
        'timeStart', timeStart, ...
        'timeFinal', timeFinal, ...
        'timeStep', timeStep, ...
        'dischargeC_rate', dischargeC_rate, ...
        'chargeC_rate', chargeC_rate, ...
        'cycle_startmode', cycle_startmode, ...
        'temperature', temperature, ...
        'working_electrode', string(working_electrode), ...
        'simulationEnd', 0, ...
        'current_mode', current_mode, ...
        'dischargeTimeStep', dischargeTimeStep, ...
        'chargeTimeStep', chargeTimeStep, ...
        'CVTimeStep', CVTimeStep, ...
        'restDuration', restDuration ...
        );
            
    timeSize = round(timeFinal/timeStep);    
    battery.SimulationParams.timeSize = timeSize;    
    
    battery.AgingParams = struct( ...
        'CCCVstatus', CCCVstatus, ...
        'current_cutoff', current_cutoff, ... 
        'cycleNum', cycleTotalNum ...
        );

    % --------------- Defaults for rest ---------------
    if ~isfield(battery.SimulationParams,'restDuration')
                battery.SimulationParams.('restDuration') = 300; % 5 minutes
    end
    if ~isfield(battery.SimulationParams,'restTimeStep')
        battery.SimulationParams.('restTimeStep') = 1;     % 1-second steps during rest
    end

    if isfield(battery.SimulationParams,'cycle_startmode')
        cycle_startmode = "discharge";
    end

    % ----- Preallocate AgingParams storage -----
    battery.AgingParams.battery{cycleTotalNum, 1} = [];
    isCCCV = strcmpi(current_mode,'CCCV');

    %% Run simulation for selected model
    for cycleNum = 1:cycleTotalNum        
        % Determine applied current using C-rate if needed
        if isCCCV
            applied_current = [];
            applied_current = DataPreprocessing.preprocessCurrent(battery, applied_current, isCCCV, ...
                dischargeC_rate, chargeC_rate, cycle_startmode, parallelCellNum);
        end

        ESPM.ESPMinitialParameters(battery, applied_current, working_electrode, cycleNum, timeStep, temperature);

         ESPMsimulation.runESPMsimulation(battery, battery.preComputedMatrix, applied_current, cycleNum, isCCCV, current_cutoff, timeSize, timeStep, parallelCellNum);

        % Save variables
        battery.AgingParams.battery{cycleNum, 1} = battery.toStruct();
       
        battery_capacity_cell = battery.ElectricalParams.cell.battery_capacity_cell;
        if battery_capacity_cell(end) < (0.5 * battery_capacity_cell(1))
             fprintf('\nCapacity dropped below 50%% at cycle %d. Stopping.\n', cycleNum);
             break
        end
        % ---- Cheap progress print ----
        runtime = battery.SimulationParams.runtime(cycleNum);  % or per-cycle entry
        fprintf('Cycle %d , runtime: %.3f s\n', cycleNum, runtime);

        % profile off
        % profile viewer
    end
end