classdef DefaultParameters

    methods(Static)

        function defaultParametersList = defineDefaultParameters()
            
            defaultParametersList = {'thickness', 'active_material_volume_fraction', ...
                'electrolyte_volume_fraction', 'particle_radius', ...
                'diffusion_coefficient_reference', 'conductivity',  ...
                'bruggeman_coefficient', 'reaction_rate_coefficient', 'concentration_maximum', ...
                'contact_resistance', ...
                'temperature_abbient', ...
                'double_layer_capacitance'};
        end

        %%
        function paramValue = extractDefaultParameters(material, domain, paramName)
    
            paramValue = NaN;  % Default if not found
        
            % Define parameter database as a struct for lookup
            % paramDB = DefaultParameters.initializeParameterDatabase();
        
            % Convert inputs to lowercase for case-insensitive comparison
            % material = lower(convertStringsToChars(material));
            % domain = lower(convertStringsToChars(domain));
            % paramName = lower(convertStringsToChars(paramName));
   
            % Check if domain exists for the material
            % if ~isfield(paramDB.(material), domain)
            %     return; % Return NaN for unsupported domain
            % end
            
            % Retrieve parameter value if it exists
            % if isfield(paramDB.(material).(domain), paramName)
            %     paramValue = paramDB.(material).(domain).(paramName);
            % end
        
            % Special handling for double-layer capacitance: set to zero if NaN or not found
            if strcmpi(paramName, 'double_layer_capacitance_neg') && (isnan(paramValue))
                paramValue = 0;
                  
            % Special handling for double-layer capacitance: set to zero if NaN or not found
            elseif strcmpi(paramName, 'double_layer_capacitance_pos') && (isnan(paramValue))
                paramValue = 0;

            else
                paramValue = NaN;
            end
        end
    
        %%
        function validateInputs(material, domain, paramName)
            if ~ischar(material) && ~isstring(material)
                throw(MException('BatteryParameters:InvalidMaterial', ...
                    'Material must be a character array or string.'));
            end
            if ~ischar(domain) && ~isstring(domain)
                throw(MException('BatteryParameters:InvalidDomain', ...
                    'Domain must be a character array or string.'));
            end
            if ~ischar(paramName) && ~isstring(paramName)
                throw(MException('BatteryParameters:InvalidParamName', ...
                    'Parameter name must be a character array or string.'));
            end
        end
    
        %%
        function paramDB = initializeParameterDatabase()
            % Initialize struct for parameter storage
            paramDB = struct();
        
            % NMC811 parameters
            paramDB.nmc811.negative = struct( ...
                'thickness_neg', 85.2e-6, ...
                'active_material_volume_fraction_neg', 0.75, ...
                'electrolyte_volume_fraction_neg', 0.25, ...
                'particle_radius_neg', 5.68e-6, ...
                'diffusion_coefficient_reference_neg', 3.3e-14, ...
                'conductivity_neg', 215, ...
                'bruggeman_coefficient_neg', 1.5, ...
                'reaction_rate_coefficient_neg', 0.835e-11, ...
                'concentration_maximum_neg', 33.133e3 ...
            );
            paramDB.nmc811.positive = struct( ...
                'thickness_pos', 75.62e-6, ...
                'active_material_volume_fraction_pos', 0.665, ...
                'electrolyte_volume_fraction_pos', 0.335, ...
                'particle_radius_pos', 5.22e-6, ...
                'diffusion_coefficient_reference_pos', 0.4e-14, ...
                'conductivity_pos', 0.18, ...
                'bruggeman_coefficient_pos', 1.5, ...
                'reaction_rate_coefficient_pos', 4.605e-11, ...
                'concentration_maximum_pos', 63.104e3 ...
            ); 
            paramDB.nmc811.separator = struct( ...
                'thickness_sep', 12.0e-6, ...
                'electrolyte_volume_fraction_sep', 0.47, ...
                'bruggeman_coefficient_sep', 1.5 ...
            );
            paramDB.nmc811.electrolyte = struct( ...
                'diffusion_coefficient_reference_elyte', 1.77e-10 ...
            );
            paramDB.nmc811.cell = struct( ...
                'contact_resistance_cell', 0 ...
            );
        
            % NMC111 parameters
            paramDB.nmc111.negative = struct( ...
                'thickness_neg', 46.6e-6, ...
                'active_material_volume_fraction_neg', 0.493, ...
                'electrolyte_volume_fraction_neg', 0.292, ...
                'particle_radius_neg', 6.3e-6, ...
                'diffusion_coefficient_reference_neg', 3.21e-14, ...
                'conductivity_neg', 1000, ...
                'bruggeman_coefficient_neg', 1.52, ...
                'reaction_rate_coefficient_neg', 1.56e-11, ...
                'concentration_maximum_neg', 31.39e3 ...
            );
            paramDB.nmc111.positive = struct( ...
                'thickness_pos', 43.0e-6, ...
                'active_material_volume_fraction_pos', 0.572, ...
                'electrolyte_volume_fraction_pos', 0.209, ...
                'particle_radius_pos', 2.13e-6, ...
                'diffusion_coefficient_reference_pos', 2.04e-14, ...
                'conductivity_pos', 10, ...
                'bruggeman_coefficient_pos', 1.62, ...
                'reaction_rate_coefficient_pos', 7.4235e-11, ...
                'concentration_maximum_pos', 48.39e3 ...
            );
            paramDB.nmc111.separator = struct( ...
                'thickness_sep', 18.7e-6, ...
                'electrolyte_volume_fraction_sep', 0.305, ...
                'bruggeman_coefficient_sep', 1.44 ...
            );
            paramDB.nmc111.cell = struct( ...
                'contact_resistance_cell', 0.534 ...
            );
    
        end
    end
end


